name: 'Setup Java and Gradle Composite Action'
description: 'Common build steps'
runs:
  using: "composite"
  steps:
    # Set up Java environment for the next steps
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8

    # Setup Gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true
