name: Build
run-name: Simple action to build plugin
# Triggered when pushing to main, develop or in a pull request
on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0

      # Set up Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      # Build plugin
      - name: Build plugin without running tests
        run: ./gradlew build -x check